apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wirewheel-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wirewheel
        tier: database
    spec:
      containers:
        - name: postgres
          image: "postgres:9.5"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ww-database-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ww-database-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ww-database-secret
                  key: database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgresql
              containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          awsElasticBlockStore:
            volumeID: "vol-0634050c55bab8bbb"
            fsType: ext4
